blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/mexamaps/mexamaps/discussions
    about: Discuss the usage of MexaMaps, ask questions, or talk about ideas that aren't yet actionable.
  - name: Translations
    url: https://github.com/mexamaps/mexamaps/blob/master/docs/TRANSLATIONS.md
    about: Translate MexaMaps into your language
  - name: News
    url: https://mexamaps.app/news/
    about: Check the latest project news
